// Generate a self-consistent Rust test fixture so `cargo test` runs the full
// distinct-error matrix WITHOUT a proving stack. The payload is sha256(SEED) so
// the test can reproduce the exact Hash<32> via env.crypto().sha256(SEED).
import * as SDK from '@stellar/stellar-sdk';
import fs from 'fs';
import { createRequire } from 'module';
import { g1Bytes, g2Bytes } from './lib.mjs';
const require = createRequire(import.meta.url);
const snarkjs = require('/Users/mac/covenant/circuits/node_modules/snarkjs');

const B = '/Users/mac/covenant';
const secret = JSON.parse(fs.readFileSync(`${B}/build/policy_secret.json`));
const vk = JSON.parse(fs.readFileSync(`${B}/circuits/build/verification_key.json`));
const AMOUNT = '10000000';
const PAYEE = process.env.PAYEE;
const TOKEN = process.env.TOKEN;

const SEED = Buffer.from('covenant-p1-fixture-payload-seed-v1');
const payload = SDK.hash(SEED); // 32 bytes = the signature_payload
const hi = BigInt('0x' + payload.subarray(0, 16).toString('hex')).toString();
const lo = BigInt('0x' + payload.subarray(16, 32).toString('hex')).toString();

const input = {
  amount: AMOUNT, dest: secret.destLeaf, policy_commitment: secret.commitment, allowlist_root: secret.root,
  sigpayload_hi: hi, sigpayload_lo: lo, cap: secret.cap, salt: secret.salt, path: secret.path, index_bits: secret.index_bits,
};
const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, `${B}/circuits/build/policy_js/policy.wasm`, `${B}/circuits/build/policy_final.zkey`);

const dec2hex32 = (d) => BigInt(d).toString(16).padStart(64, '0');
const ics = vk.IC.map((p) => g1Bytes(p).toString('hex'));

const rs = `// AUTO-GENERATED by scripts/gen_fixture.mjs — committed so \`cargo test\` runs the
// full distinct-error matrix with no proving stack. Do not edit by hand.
pub const VK_ALPHA: &str = "${g1Bytes(vk.vk_alpha_1).toString('hex')}";
pub const VK_BETA: &str = "${g2Bytes(vk.vk_beta_2, 'c1c0').toString('hex')}";
pub const VK_GAMMA: &str = "${g2Bytes(vk.vk_gamma_2, 'c1c0').toString('hex')}";
pub const VK_DELTA: &str = "${g2Bytes(vk.vk_delta_2, 'c1c0').toString('hex')}";
pub const VK_IC: [&str; ${ics.length}] = [${ics.map((h) => `"${h}"`).join(', ')}];
pub const PROOF_A: &str = "${g1Bytes(proof.pi_a).toString('hex')}";
pub const PROOF_B: &str = "${g2Bytes(proof.pi_b, 'c1c0').toString('hex')}";
pub const PROOF_C: &str = "${g1Bytes(proof.pi_c).toString('hex')}";
// public signals (32-byte big-endian hex): [amount, dest, commitment, root, sphi, splo]
pub const PUB: [&str; 6] = [${publicSignals.map((s) => `"${dec2hex32(s)}"`).join(', ')}];
pub const COMMITMENT: &str = "${dec2hex32(secret.commitment)}";
pub const ROOT: &str = "${dec2hex32(secret.root)}";
pub const PAYLOAD_SEED: &[u8] = b"covenant-p1-fixture-payload-seed-v1";
pub const AMOUNT: i128 = ${AMOUNT};
pub const PAYEE: &str = "${PAYEE}";
pub const TOKEN: &str = "${TOKEN}";
`;
fs.writeFileSync(`${B}/contracts/covenant_account/src/fixture_data.rs`, rs);
console.log('wrote fixture_data.rs; publicSignals=', publicSignals.join(','));
