// Emit web/lib/poseidon.js: a self-contained, dependency-free browser Poseidon(2) (poseidon-lite,
// verified byte-identical to circomlibjs / the circuit) + a sparse DEPTH-16 allowlist tree builder.
import fs from 'fs';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const C2 = require('/tmp/plite/node_modules/poseidon-lite/constants/2.js').default; // {C:[b64...], M:[[b64...]]}

const body = `// AUTO-GENERATED by scripts/gen_poseidon_browser.mjs — do not edit by hand.
// Dependency-free Poseidon(2) over BN254 (poseidon-lite constants; verified byte-identical to
// circomlibjs and the policy circuit) + a sparse DEPTH-16 allowlist Merkle builder. Pure BigInt,
// runs entirely in the browser — the cap, salt and allowlist NEVER leave this file's caller.
(function () {
  'use strict';
  var F = BigInt('21888242871839275222246405745257275088548364400416034343698204186575808495617');
  var N_ROUNDS_F = 8;
  var N_ROUNDS_P = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68];
  var RAW = ${JSON.stringify(C2)};
  function unstring(o) {
    if (Array.isArray(o)) return o.map(unstring);
    var bytes = Uint8Array.from(atob(o), function (c) { return c.charCodeAt(0); });
    var hex = Array.from(bytes).map(function (x) { return x.toString(16).padStart(2, '0'); }).join('');
    return BigInt('0x' + hex);
  }
  var CONST = { C: unstring(RAW.C), M: unstring(RAW.M) };
  function pow5(v) { var o = v * v; return v * o * o % F; }
  function mix(state, M) {
    var out = [];
    for (var x = 0; x < state.length; x++) { var o = 0n; for (var y = 0; y < state.length; y++) o = o + M[x][y] * state[y]; out.push(o % F); }
    return out;
  }
  // poseidon over n inputs (here always 2 -> t=3), identical algorithm to poseidon-lite/circomlib.
  function poseidon(inputs) {
    var ins = inputs.map(function (i) { return BigInt(i) % F; });
    var t = ins.length + 1;
    var nRoundsP = N_ROUNDS_P[t - 2];
    var C = CONST.C, M = CONST.M;
    var state = [0n].concat(ins);
    for (var x = 0; x < N_ROUNDS_F + nRoundsP; x++) {
      for (var y = 0; y < state.length; y++) {
        state[y] = state[y] + C[x * t + y];
        if (x < N_ROUNDS_F / 2 || x >= N_ROUNDS_F / 2 + nRoundsP) state[y] = pow5(state[y]);
        else if (y === 0) state[y] = pow5(state[y]);
      }
      state = mix(state, M);
    }
    return state[0];
  }
  var poseidon2 = function (a, b) { return poseidon([a, b]); };

  var DEPTH = 16, LEAVES = 1 << DEPTH, ZERO = 0n;
  function zeroHashes() { var z = [ZERO]; for (var l = 1; l <= DEPTH; l++) z.push(poseidon2(z[l - 1], z[l - 1])); return z; }

  // Build a DEPTH-16 allowlist policy from cap + salt + allowlist (array of dest_field decimal strings).
  // Members occupy indices 0..N-1; all other leaves are ZERO. Returns the commitment, root, and a
  // per-member membership path (siblings + index bits) — exactly what the prover consumes.
  function buildPolicy(capStroops, saltDec, allowlistFields) {
    if (!allowlistFields || !allowlistFields.length) throw new Error('allowlist must have at least one address');
    if (allowlistFields.length > LEAVES) throw new Error('allowlist too large for DEPTH-16');
    var z = zeroHashes();
    var leaves = allowlistFields.map(function (d) { return BigInt(d); });
    var levels = [leaves.slice()];
    var level = leaves.slice();
    for (var l = 0; l < DEPTH; l++) {
      var next = [];
      for (var i = 0; i < level.length; i += 2) {
        var left = level[i];
        var right = (i + 1 < level.length) ? level[i + 1] : z[l];
        next.push(poseidon2(left, right));
      }
      level = next.length ? next : [z[l + 1]];
      levels.push(level);
    }
    var root = level[0];
    var members = allowlistFields.map(function (d, idx) {
      var i = idx, path = [], bits = [];
      for (var l = 0; l < DEPTH; l++) {
        var sib = i ^ 1;
        var arr = levels[l];
        var sibVal = (sib < arr.length) ? arr[sib] : z[l];
        path.push(sibVal.toString());
        bits.push((i & 1).toString());
        i >>= 1;
      }
      return { destLeaf: BigInt(d).toString(), index: idx, path: path, index_bits: bits };
    });
    return { commitment: poseidon2(BigInt(capStroops), BigInt(saltDec)).toString(), root: root.toString(), members: members };
  }

  // Verify a member's path reproduces the root (internal consistency / circuit-equivalence check).
  function verifyMember(root, destLeaf, path, index_bits) {
    var h = BigInt(destLeaf);
    for (var l = 0; l < DEPTH; l++) h = index_bits[l] === '0' ? poseidon2(h, BigInt(path[l])) : poseidon2(BigInt(path[l]), h);
    return h.toString() === String(root);
  }

  // Address -> field element, IDENTICAL to the contract's dest_field:
  // U256(sha256(xdr(ScVal::Address)) with the top byte zeroed), big-endian. Fully client-side
  // (no RPC) so the allowlist — including unexercised entries — never leaves the browser.
  function addrToField(addrStr) {
    var SDK = window.StellarSdk;
    var xdr = SDK.Address.fromString(addrStr).toScVal().toXDR();
    var h = window.Buffer.from(SDK.hash(xdr));
    h[0] = 0;
    return BigInt('0x' + h.toString('hex')).toString();
  }
  // Build a policy directly from allowlist ADDRESSES (encodes them client-side first).
  function buildPolicyForAddresses(capStroops, saltDec, addrs) {
    return buildPolicy(capStroops, saltDec, (addrs || []).map(addrToField));
  }

  window.CovenantPoseidon = { poseidon2: function (a, b) { return poseidon2(a, b).toString(); }, buildPolicy: buildPolicy, buildPolicyForAddresses: buildPolicyForAddresses, addrToField: addrToField, verifyMember: verifyMember, DEPTH: DEPTH };
})();
`;
fs.writeFileSync('/Users/mac/covenant/web/lib/poseidon.js', body);
console.log('wrote web/lib/poseidon.js (' + body.length + ' bytes)');
